# .travis.yml
# Configure Travis CI service for http://github.com/PDAL
language: cpp


sudo:
    required

services:
    docker

compiler:
  - gcc

env:
  - PDAL_OPTIONAL_COMPONENTS=all
  - PDAL_OPTIONAL_COMPONENTS=none


before_install: ./scripts/ci/before_install.sh

script:
    docker run -v $TRAVIS_BUILD_DIR:/pdal -e CXX="$CXX" -e CC="$CC" -e PDAL_OPTIONAL_COMPONENTS="$PDAL_OPTIONAL_COMPONENTS" -t pdal/dependencies:latest /bin/sh -c "/pdal/scripts/ci/script.sh"

after_success:
  - echo "secure travis:" "$TRAVIS_SECURE_ENV_VARS"
  - sh -c 'if test "$TRAVIS_SECURE_ENV_VARS" = "true" -a "$TRAVIS_BRANCH" = "1.3-maintenance" -a "$PDAL_OPTIONAL_COMPONENTS" = "all"; then echo "publish website"; ./scripts/ci/build_docs.sh; ./scripts/ci/add_deploy_key.sh; ./scripts/ci/deploy_website.sh $TRAVIS_BUILD_DIR/doc/build /tmp; fi'

notifications:
  on_success: always
  on_failure: always
  irc: chat.freenode.net#pdal
  slack:
    rooms:
      secure: AjatYRAUpsczjENkpHPFiLLZ/leDlzx4TH+oPQYZCpA4WpJdNRy0IB4oMR2IYiY+qz0nHDbeMTBvF0l8S6NknZAz20f8buf4IkrdXymBQBOTmLHMWbpgHuSCCu7xMwtG6thjMEmBOXm5UgCcdqvlchcaoAUunyprXQWgJwI+tHE=
    on_failure: always
    on_success: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4c7f3edec32936d6a758
