name: Conda

on:
    push:
        paths-ignore:
            - 'doc/**'
    pull_request:
        paths-ignore:
            - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Conda ${{ matrix.platform }}
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: true
      matrix:
        platform: ['windows-latest','macos-latest','ubuntu-latest']

    env:
      PDAL_PLATFORM: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3

    - name: Support longpaths
      run: git config --system core.longpaths true
      if: matrix.platform == 'windows-latest'

    - uses: mamba-org/setup-micromamba@v1
      with:
        init-shell: bash powershell cmd.exe
        environment-file: scripts/ci/environment.yml
        environment-name: "pdal-build"
        cache-environment: true
        cache-downloads: true

    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.platform == 'windows-latest'

    - name: Setup
      run: |
          source ./scripts/ci/conda/setup.sh

    - name: Build
      run: |
          source ../scripts/ci/conda/compile.sh
      working-directory: ./pdal-feedstock

    - name: Debug
      run: |
          conda activate test
          conda info
          conda list

    - name: Test
      run: |
          source ./scripts/ci/conda/examples.sh

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.platform }}-conda-package
        path: ./pdal-feedstock/packages/

    - name: Deploy to pdal-master Conda channel
      if: github.ref == 'refs/heads/master'
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
          source ../scripts/ci/conda/upload.sh || true
      working-directory: ./pdal-feedstock
